### ISSUE TITLE
Org literals using colon notation are not converted well

### ISSUE THREAD

**Issue by pgfoster** [masayuko/ox-rst#16]
Here are a couple of examples from the org manual

```
* This literal works well

#+BEGIN_EXAMPLE
Some example from a text file.
#+END_EXAMPLE

* This literal does not work well

Here is an example
    : Some example from a text file.
```

One problem here is that the second pair of back-ticks ends up on a line by itself.

```
``Some example from a text file.
``
```

**Comment by masayuko** [comment]
I believe I have fixed this issue last night. Please update ox-rst and try one.

**Comment by pgfoster** [comment]
I'm getting the same thing.  This

    : foo
    : bar

exports as 

```
``foo
bar
``
```

Perhaps it should be

```
::

    foo
    bar
```

which is what I get from

```
#+BEGIN_EXAMPLE
foo
bar
#+END_EXAMPLE
```

**Comment by masayuko** [comment]
the #+BEGIN_EXAMPLE..#+END_EXAMPLE form is process as the example-block.
:foo form is process as the verbatim.
This behavior is by design too.

**Comment by pgfoster** [comment]
It appears that in the org manual
http://orgmode.org/org.html#Literal-examples
the #+BEGIN_EXAMPLE..#+END_EXAMPLE and the colon notation are two forms of the same thing, both for literals.

I often execute code blocks in org-mode, using C-c C-c.  If the output is short it uses the colon form for literal output, and if the output is long it uses #+begin_example  ... #+end_example form for literal output.  Org appears to be using two different but equivalent notations for the same thing --- literals.  Should rst output mimic that equivalence?

In any event, I don't think the second pair of backticks should be on a line by itself.  Is that not a problem?

**Comment by masayuko** [comment]
I know you mean and the org manual. 
But the backends of ox sense different by the ox framework design.

**Comment by masayuko** [comment]
I have already fixed for about backticks problem last night.

**Comment by pgfoster** [comment]
Ah, you are quite right -- thanks muchly for your proactive fix.  I had updated to your most recent code but I neglected to reload into emacs, so I did not see it.  Doh!  But after I finally figured that out, a smaller problem remains.   When I export

```
: foo
```
I get
```
``foo ``
```
I think that is a problem because the second set of backticks is surrounded by whitespace.  When I used that as input into sphinx, it gives me

    WARNING: Inline literal start-string without end-string.

and it is not formatted as a literal.  When I get rid of the extra space the warning goes away and it is formatted as a literal.

Org does not appear to be consistent in distinguishing between the two forms, the #+BEGIN_EXAMPLE ... #+END_EXAMPLE and the colon notation.  When I export these lines

```
: foo

#+BEGIN_EXAMPLE
foo
#+END_EXAMPLE
```
as html, I get

```
<pre class="example">
foo
</pre>

<pre class="example">
foo
</pre>
```

So the two forms are being treated exactly the same by the html exporter. That is what I was used to.

How might the two forms be treated the same in the rst exporter?

**Comment by pgfoster** [comment]
It looks like the two forms for literal are treated in the same way by markdown export and by latex export as well.   So this ---

```
: foo
: bar

#+BEGIN_EXAMPLE
foo
bar
#+END_EXAMPLE
```
is exported to 

```
    foo
    bar

    foo
    bar
```
by markdown export, and 
```
\begin{verbatim}
foo
bar
\end{verbatim}

\begin{verbatim}
foo
bar
\end{verbatim}
```
by latex export.

Rst export seems to be unusual in distinguishing between them.  It exports as

```
``foo bar ``

::

    foo
    bar
```
unusually putting the colon-marked up literal on a single line.

**Comment by masayuko** [comment]
OK, I will fix extra space problem, please wait a sec.

markup text surrounded by =  and lines started : are treated as verbatim.
In rst case, I think it should be exported as inline form.

In the following case that numbered list line including verbatim:

```
1. =this= verbatim form is inline
```

```
1.

::

    this

verbatim form is inline
```

is invalid.

**Comment by masayuko** [comment]
Hmm, Ok I will check other backends code.

**Comment by pgfoster** [comment]
That would be great if you could, thanks.  Html, markdown, and latex exports all distinguish between text marked up with = and lines that start with :.  Rst export is unusual in treating them the same way.  I wish I could help with the code, but I am useless with lisp.  Good luck with it!  All this is going to be very useful to those of us who write in org-mode but deploy in sphinx.

**Comment by masayuko** [comment]
Thank you let me know!
